set_property PACKAGE_PIN F3 [get_ports {a[7]}]
set_property IOSTANDARD LVCOMS33 [get_ports {a[7]}]
set_property PACKAGE_PIN H4 [get_ports {a[6]}]
set_property IOSTANDARD LVCOMS33 [get_ports {a[6]}]
set_property PACKAGE_PIN N4 [get_ports {a[5]}]
set_property IOSTANDARD LVCOMS33 [get_ports {a[5]}]
set_property PACKAGE_PIN R2 [get_ports {a[4]}]
set_property IOSTANDARD LVCOMS33 [get_ports {a[4]}]
set_property PACKAGE_PIN R3 [get_ports {a[3]}]
set_property IOSTANDARD LVCOMS33 [get_ports {a[3]}]
set_property PACKAGE_PIN P4 [get_ports {a[2]}]
set_property IOSTANDARD LVCOMS33 [get_ports {a[2]}]
set_property PACKAGE_PIN R5 [get_ports {a[1]}]
set_property IOSTANDARD LVCOMS33 [get_ports {a[1]}]
set_property PACKAGE_PIN P6 [get_ports {a[0]}]
set_property IOSTANDARD LVCOMS33 [get_ports {a[0]}]

set_property PACKAGE_PIN D4 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

set_property PACKAGE_PIN T10 [get_ports b]
set_property IOSTANDARD LVCMOS18 [get_ports b]

set_property PACKAGE_PIN L13 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[7]}]
set_property PACKAGE_PIN M14 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[6]}]
set_property PACKAGE_PIN P13 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[5]}]
set_property PACKAGE_PIN K12 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[4]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[3]}]
set_property PACKAGE_PIN L14 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[2]}]
set_property PACKAGE_PIN N12 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[1]}]
set_property PACKAGE_PIN P11 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[0]}]

set_property PACKAGE_PIN N11 [get_ports {en[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {en[5]}]
set_property PACKAGE_PIN N14 [get_ports {en[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {en[4]}]
set_property PACKAGE_PIN N13 [get_ports {en[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {en[3]}]
set_property PACKAGE_PIN M12 [get_ports {en[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {en[2]}]
set_property PACKAGE_PIN H13 [get_ports {en[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {en[1]}]
set_property PACKAGE_PIN G12 [get_ports {en[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {en[0]}]

set_property PACKAGE_PIN R10 [get_ports c]
set_property IOSTANDARD LVCMOS18 [get_ports c]